CREATE DATABASE GroupA;
USE GroupA;


CREATE TABLE IF NOT EXISTS City(
	City_ID int auto_increment primary key,
    City_Name varchar(255)
);

CREATE TABLE Village(
	Village_ID int auto_increment primary key, 
	Village_Name varchar(255),
    City_ID int,
    foreign key(City_ID)
    references City(City_ID) 
    on delete cascade
);
    
CREATE TABLE IF NOT EXISTS Accounts(
	Client_ID int auto_increment primary key, 
    Client_Name varchar(255) not null, 
    Village_ID int,
    foreign key(Village_ID)
    references Village(Village_ID) 
    on delete cascade
);

CREATE TABLE IF NOT EXISTS Monthly_Bill(
	Bill_ID int auto_increment primary key, 
    Client_ID int,
    Bill_Date date,
    Due_Date date,
    Bill_Amount float,
	foreign key (Client_ID)
    references Accounts(Client_ID)
    on delete cascade
);

INSERT INTO Monthly_Bill(Client_ID)
SELECT Client_ID FROM Accounts;

INSERT INTO City(City_Name) 
VALUES 
	('Muntinlupa'), 
	('Las Piñas'), 
	('Parañaque'),
    ('Bacoor'),
    ('Imus'),
    ('Dasmariñas'),
    ('Lipa'),
    ('Makati'),
    ('Pasig'),
    ('Taguig'),
    ('Quezon'),
    ('Mandaluyong'),
    ('Baguio'),
    ('Cebu'),
    ('Antipolo'),
    ('Pasay'),
    ('Manila'),
    ('Davao'),
    ('Baguio'),
    ('Bacolod'),
    ('Iloilo'),
    ('Cagayan de Oro'),
    ('Manadaue'),
    ('Zamabales'),
    ('Caloocan'),
    ('Angeles'),
    ('Marikina'),
    ('Talisay'),
    ('Tacloban'),
    ('Dumaguete'),
    ('Tagbilaran'),
    ('Silay'),
    ('Legazpi'),
    ('Samal'),
    ('Cotabato'),
    ('Iligan'),
    ('Ozamis'),
    ('Bataan'),
    ('Danao'),
    ('Victorias'),
    ('Butuan'),
    ('Batangas'),
    ('San Fernando'),
    ('San Carlos'),
    ('Vigan'),
    ('Dagupan'),
    ('Laoag'),
    ('Tuguegarao'),
    ('Tagaytay'),
    ('Catbalogan'),
    ('Navotas'),
    ('Roxas'),
    ('Sagay'),
    ('Passi'),
    ('Tangub'),
    ('Tanjay'),
    ('Tacurong'),
    ('Valencia'),
    ('Zamboanga'),
    ('Binan'),
    ('Bayawan'),
    ('Bogo'),
    ('Borongan'),
    ('Cabadbaran'),
    ('Mansilingan'),
    ('Montevista'),
    ('Bais'),
    ('Batac'),
    ('Abuanan'),
    ('Caridad'),
    ('Calumangan'),
    ('Atipulan'),
    ('Bagroy'),
    ('Busay'),
    ('Tabunan'),
    ('Ilijan'),
    ('Pacol'),
    ('Napoles'),
    ('Oranbo'),
    ('Pataliw'),
    ('San Antonio'),
    ('San Joaquin'),
    ('San Jose'),
    ('Kalawaan'),
    ('Bambang'),
    ('Bagong Katipunan'),
    ('San Benito'),
    ('Latag'),
    ('San Celestino'),
    ('San Lucas'),
    ('Mabunao'),
    ('Manlipac'),
    ('Olympia'),
    ('Dansulan'),
    ('Cambaguio'),
    ('Cabanlutan'),
    ('Consolacion'),
    ('Hangyad'),
    ('Canlarago'),
    ('Cambulao')
;
    
INSERT INTO Village(Village_Name, City_ID)
VALUES
	('Alabang', 1),
    ('Ayala Alabang', 1),
    ('Bayanan', 1),
    ('Cupang', 1),
    ('Poblacion', 1),
    ('Putatan', 1),
    ('Sucat', 1),
    ('Tunasan', 1),
    ('Almanza Uno', 2),
    ('Almanza Dos', 2),
    ('BF International', 2),
    ('Daniel Fajardo', 2),
    ('Elias Aldana', 2),
    ('Ilaya', 2),
    ('Manuyo Uno', 2),
    ('Manuyo Dos', 2),
	('Pilar', 2),
	('Pulang Lupa Uno', 2),
    ('Zapote', 2),
	('Baclaran', 3),
    ('BF Homes', 3),
	('La Huerta', 3),
    ('Marcelo Green', 3),
    ('Moonwalk', 3),
    ('San Antonio', 3),
	('San Dionisio', 3),
	('San Isidro', 3),
	('San Martin de Porres', 3),
	('Sto. Niño', 3),
	('Tambo', 3),
	('Vitalez', 3),
	('BANALO', 4),
	('BAYANAN', 4),
	('CAMPO SANTO', 4),
	('DAAN BUKID', 4),
	('DIGMAN', 4),
	('KAINGIN', 4),
	('MABOLO I', 4),
    ('ALAPAN I-A', 5),
	('ALAPAN I-B', 5),
	('ALAPAN I-C', 5),
	('BUCANDALA I', 5),
	('PAG-ASA I', 5),
	('PAG-ASA II', 5),
	('PAG-ASA III', 5),
('San Andres II', 6),
('San Antonio De Padua', 6),
('San Antonio De Padua II', 6),
('San Dionisio', 6),
('San Esteban', 6),
('San Francisco', 6),
('San Francisco II', 6),
('San Jose', 6),
('San Juan', 6),
('San Lorenzo Ruiz I', 6),
('San Lorenzo Ruiz II', 6),
('Balintawak', 7),
('Marawoy', 7),
('Dagatan', 7),
('Lumbang', 7),
('Talisay', 7),
('Inosluban', 7),
('Plaridel', 7),
('Bangkal', 8),	
('Bel-Air', 8),	
('Carmona', 8),	
('Cembo', 8),	
('Comembo', 8),	
('Dasmariñas', 8),	
('East Rembo', 8),	
('Forbes Park', 8),	
('Malinao', 9),		
('Manggahanb', 9),	
('Maybunga', 9),	
	('Pineda', 9),
	('Rosario', 9),
	('Sagád', 9),
	('San Antonio', 9),
	('San Joaquín', 9),
	('Bata', 18),
	('Cabug', 18),
	('Estefanía', 18),
	('Felisa', 18),
	('Granada', 18),
	('Handumanan', 18),
	('Mandalagan', 18),
    ('Bayombong', 50),
	('Bambang', 50),
	('Lagawe', 50),
	('La trinidad', 50),
	('nangalisan', 60),
	('Ambukiao', 61),
	('Kapangan', 62),
	('San Juan', 50),
	('Rosario', 84),
	('Aringay', 84),
    ('Adlawon', 83),
	('Agsngot', 51),
	('Apas', 51),
	('Babag', 51),
	('Acay', 85),
	('Banawa', 86),
	('Banilad', 51),
	('Cruz', 51),
	('Santo Nino', 88),
	('Sawang Calero', 87),
	('Calamba', 89),
	('Parian', 90),
	('Paril', 51),
	('Cogon', 51),
    ('Bagong Nayon',53),
	('Berverly Hills',53),
	('Calawis',91),
	('Cupang', 92),
	('Dalig',93),
	('Dela Paz',94),
	('Mambugan',95),
	('San Luis',96),
	('San Roque',97),
	('Santa Cruz',98),
	('Rodriguez',99),
	('San Mateo',100); 

INSERT INTO Accounts(Client_Name, Village_ID)
VALUES
	('Santos', 41),
    ('Reyes', 30),
    ('Cruz', 6),
    ('Bautista', 21),
    ('Ocampo', 36),
    ('Garcia', 17),
    ('Mendoza', 44),
    ('Torres', 38),
    ('Andrada', 41),
    ('Castillo', 12),
    ('Flores', 12),
    ('Villanueva', 32),
    ('Rivera', 14),
    ('Aquino', 22),
    ('Navarro', 3),
    ('Ramos', 4),
    ('Salazar', 2),
    ('Ramos', 25),
    ('Castro', 35),
    ('Mercado', 42),
    ('de la Cruz', 8),
    ('de la Reyes', 24),
    ('del Rosario', 34),
    ('de los Santos', 41),
    ('de Guzman', 10),
    ('de Castro', 23),
    ('de la Vega', 42),
    ('de la Rosa', 43),
    ('de Asis', 11),
    ('de Rosales', 39),
    ('Divinagracia', 37),
    ('Ortiz', 37),
    ('Marcos', 14),
    ('Lacson', 13),
    ('Padilla', 43),
    ('Macapagal', 45),
    ('Martinez', 38),
    ('Gonzales', 1),
    ('Francisco', 9),
    ('Rodriguez', 26),
    ('Magbanua', 41),
    ('Sanchez', 4),
    ('Alonzo', 33),
    ('Vizcarra', 13),
    ('Macarayan', 30),
    ('Lasmarias', 29),
    ('Gamayao', 7),
    ('Aman', 5),
    ('Bravo', 12),
    ('Reomales', 9),
    ('Aguilar', 24),
    ('Alarcon', 2),
    ('Alcantara', 25),
    ('Alejandro', 43),
    ('Alfonso', 5),
    ('Almonte', 17),
    ('Alterado', 17),
    ('Alvarez', 3),
    ('Argente', 32),
    ('Belmonte', 29),
    ('Benitez', 18),
    ('Bernal', 29),
    ('Buenavetura', 12),
    ('Camacho', 1),
    ('Chavez', 11),
    ('Chiu', 37),
    ('Clemente', 40),
    ('Chua', 4),
    ('Coronel', 11),
    ('Corpuz', 21),
    ('Dacanay', 13),
    ('Dacua', 7),
    ('Dagohoy', 8),
    ('Dalangin', 39),
    ('Dalisay', 32),
    ('Dandan', 10),
    ('Danila', 43),
    ('David', 4),
    ('Dee', 33),
    ('De Castro', 12),
    ('De  Jesus', 42),
    ('De Leon', 44),
    ('De Silva', 8),
    ('De Vera', 40),
    ('Del Castillo', 5),
    ('Del Prado', 33),
    ('Del Rosario', 39),
    ('Del Valle', 1),
    ('Delos Santos', 29),
    ('Diaz', 45),
    ('Driz"', 28),
    ('Dimaano', 5),
    ('Dimacalli', 44),
    ('Dimagiba', 3),
    ('Dimapilis', 30),
    ('Dimatatac', 43),
    ('Dizon', 36),
    ('Donato', 37),
    ('Gacutan', 35),
    ('Gallardo', 13),
    ('Galvez', 3),
    ('Garcia', 5), 
    ('Gardiola', 27),
    ('Fabela', 41),
    ('Ferrer', 37),
    ('Fuentes', 20),
    ('Fulgencio', 40),
    ('fritz', 17),
    ('Frias', 2),
    ('Flores', 41),
    ('Halili', 44),
    ('Hernandez', 10),
    ('Hermoso', 5),
    ('Hipolito', 44),
    ('Jaranilla', 5),
    ('Jimenez', 3),
    ('Jadina', 43),
    ('Jardin', 15),
    ('Kong', 14),
    ('Lopoz', 3),
    ('Luna', 19),
    ('Lucero', 23),
    ('Luna', 8),
    ('Lumbres', 21),
    ('Macalinga', 24),
    ('Mata', 38),
    ('Mejo', 16),
    ('Mendez', 38),
    ('Mejia', 38),
    ('Mendiola', 30),
    ('Maranan', 22),
    ('Madrid', 27),
    ('Marquez', 18),
    ('Mateo', 25),
    ('Medina', 3),
    ('Marcelino', 26),
    ('Nofueno', 3), 
    ('Nicolas', 28), 
    ('Nicol', 42),
    ('Nolasco', 43),
    ('Navid', 35),
    ('Olarte', 35),
    ('Pecson', 8),
    ('Pelaez', 23),
    ('Peralta', 42),
    ('Perez', 30),
    ('Paulino', 41),
    ('Que', 2),
    ('Ramirez', 15),
    ('Ronres', 23),
    ('Rio', 29),
    ('Romero', 18),
    ('Riego', 44),
    ('Roce', 22),
    ('Ubalde', 10),
    ('Umali', 29),
    ('Tobias', 11),
    ('Tulfo', 41),
    ('Tabina', 26),
    ('Valdez', 20),
    ('Vicente', 39),
    ('Vicedo', 34),
    ('Vicente', 42),
    ('Villamor', 1),
    ('Viray', 14), 
    ('Villaluz', 3),
    ('Tensuan', 45),
    ('Penolio', 16),
    ('Yabut', 14),
    ('Yacapin', 16),
    ('Yadao', 17),
    ('Sabado', 3),
    ('Bayogo', 22),
    ('Yasay', 41),
    ('Ynares', 42),
    ('Yadao', 8),
    ('Zalbata', 33),
    ('Zamora', 2),
    ('Zapanta', 10),
    ('Zaragosa', 42),
    ('Zarte', 7),
    ('Eusebio', 13),
    ('Evangelista', 13),
    ('Evangelio', 16),
    ('Esguerra', 19),
    ('Espejo', 35),
    ('Salamatin', 4),
    ('Esinosa', 14),
    ('Parro', 8),
    ('Batungbacal', 11),
    ('Remot', 24),
    ('Danguilan', 4),
    ('Posada', 26),
    ('Santiago', 8),
    ('Bartolome', 5),
    ('Javier', 39),
    ('Miranda', 12),
    ('Yap', 1),
    ('Sarmiento', 3),
    ('Pineda', 6),
    ('Gatmin', 33),
	('Smith',45),
	('Johnson',7),
	('Williams', 3),
	('Jones', 4),
	('Brown', 11),
	('Davis', 23),
	('Miller', 38),
	('Wilson', 43),
	('Moore', 13),
	('Taylor', 9),
	('Anderson', 12),
	('Thomas', 22),
	('Jackson', 19),
	('White', 42),
	('Harris', 26),
	('Martin', 40),
	('thompson', 9),
	('Garcia', 15),
	('Martinez', 10),
	('Robinson', 22),
	('Clark', 43),
	('Rodriguez', 24),
	('Lewis', 44),
	('Lee', 28),
	('Walker', 6),
	('Hall', 36),
	('Allen', 16),
	('Young', 26),
	('Hernandez', 34),
	('King', 1),
	('Wright', 29),
	('Lopez', 39),
	('Hill', 34),
	('scott', 43),
	('Green', 26), 
	('Adams', 44),
	('Baker', 2),
	('Gonzalez', 20),
	('Nelson', 24),
	('Carter', 17),
	('Mitchell', 15),
	('Perez', 35),
	('Roberts', 21),
	('Turner', 29),
	('Phillips', 28),
	('Campbell', 18),
	('Parker', 35),
	('Evans', 9),
	('Edwards', 45),
	('Collins', 10),
	('Stewart', 38),
	('Sanchez', 30),
	('Morris', 10),
	('Rogers', 19),
	('Reed', 34),
	('Cook', 12),
	('Morgan', 26),
	('Bell', 14),
	('Murphy', 1),
	('Bailey', 8),
	('Rivera', 16),
	('Cooper', 28),
	('Richardson', 9),
	('Cox', 10), 
	('Howard', 11),
	('Ward', 20),
	('Torres', 37), 
	('Peterson', 35),
	('Gray', 21),
	('Ramirez', 42),
	('James', 5), 
	('Watson', 36),
	('Brooks', 2),
	('Kelly', 6),
	('Price', 25),
	('Bennett', 44),
	('Wood', 29),
	('Barnes', 5),
	('Ross', 30),	
	('Henderson', 7),
	('Coleman', 41),
	('Jenkins', 38),
	('Perry', 25),
	('Powell', 8), 
	('Long', 14),
	('Patterson', 13),	
	('Huges', 22),	
	('Flores', 30),
	('Washington', 29),
	('Butler', 39),
	('Simmons', 45),
	('Foster', 41),
	('Gonzales', 40),
	('Bryant', 45),
	('Alexander', 19),
	('Rusell', 14),
	('Griffin', 4),
	('Diaz', 13),
	('Hayes', 16)
;